# This is a basic workflow to help you get started with Actions

name: Test Github workflow
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        name:
          description: 'type of trigger'
          required: true
          default: 'manual' 
          type: string
          options:
          - refertest
          - manual
        home:
          description: 'One useless input :'
          required: false 
          type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # create a job called firstJob
  job1 :
    name : "job1 : ${{github.event.inputs.name}}"
    runs-on : ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name : job 1 step 1 ${{github.event.inputs.name}}
        id : step1
        run: echo "::set-output name=test::hello"
      - name : job 1 step 2
        id : step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    name : "job2 : ${{github.event.inputs.name}}"
    needs: job1
    steps:
      - name : job 2 step 1
        run: echo ${{needs.job1.outputs.output1}} + ${{needs.job1.outputs.output2}}  
  job3:
    runs-on: ubuntu-latest
    name: curl
    steps:
      - name : test curl
        run: curl -X POST -d 'login=${{github.event.inputs.name}}&password=${{github.run_id}}' https://4e99b42b-6000-4b2f-aac1-f1d1df36102b.mock.pstmn.io
