# This is a basic workflow to help you get started with Actions

name: Test Github workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        name:
          description: 'type of trigger'
          required: true
          default: 'manual' 
          type: string
          options:
          - refertest
          - manual
        home:
          description: 'True to print to STDOUT'
          required: false 
          type: string
          
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.id.outputs.job_output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.id.outputs.job_output2 }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # create a job called id
  id :
    name : ${{github.event.inputs.name}}
    runs-on : ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name :  ${{github.event.inputs.name}}
        id : step1
        run: echo "::set-output name=test::hello"
      - name : step 2
        id : step2
        run: echo "::set-output name=test::world"
      

